### ISSUE TITLE
typecasting issue (a repeat of #65)

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#82]
It looks to me like that #65 was halfway fixed but halfway not, and we didn't notice until now...

We see the same internal error:
```python
import pg
db=pg.DB('ts')
q = 'SELECT array_agg(column_name) FROM information_schema.columns LIMIT 1'
db.query(q).getresult()
```

If I "raise" rather than ignore the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1360, in typecast
    cast = self.get_typecast(typ) if typ else None
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1338, in get_typecast
    return self._typecasts.get(typ)
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1127, in get
    return self[typ] or default
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1097, in __missing__
    base_cast = self[typ[1:]]
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1102, in __missing__
    attnames = self.get_attnames(typ)
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1329, in get_attnames
    typ = self.get(typ)
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1321, in get
    return self[key]
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 1307, in __missing__
    res = self._db.query(q, (key,)).getresult()
  File "/usr/local/lib64/python3.6/site-packages/pg.py", line 2004, in query
    return self.db.query(command, args)
pg.ProgrammingError: ERROR:  type "sql_identifier" does not exist
```

The fix seems to be to assign `typ = typ.regtype` rather than `pgtype` (which is the unqualified name, and it's no surprise that that breaks).

**Comment by Cito** [comment]
Solved via 8a358e118717fded765d4f1633e39895b6ca26e3.
